name: Build iOS Tweak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          # Install Theos (This requires a macOS runner)
          git clone --recursive https://github.com/theos/theos.git
          export THEOS=$(pwd)/theos
          export PATH=$THEOS/bin:$PATH
          echo "Theos installation complete."

      - name: Set up environment variables
        run: |
          export TARGET=iphone:clang:latest:7.0  # Adjust this if targeting a different iOS version
          export THEOS=$PWD/theos
          export PATH=$THEOS/bin:$PATH

      - name: Find BlockNet.m file
        id: find_blocknet_m
        run: |
          # Search for BlockNet.m file in the repository
          BLOCKNET_M_PATH=$(find . -name 'BlockNet.m' -print -quit)

          if [ -z "$BLOCKNET_M_PATH" ]; then
            echo "BlockNet.m not found!"
            exit 1
          fi

          echo "BlockNet.m found at $BLOCKNET_M_PATH"

          # Save the path for later use
          echo "::set-output name=blocknet_m::$BLOCKNET_M_PATH"

      - name: Generate Makefile if missing
        run: |
          # Automatically create a Makefile if it doesn't exist
          MAKEFILE_PATH="${{ steps.find_blocknet_m.outputs.blocknet_m }}"
          MAKEFILE_DIR=$(dirname "$MAKEFILE_PATH")
          
          if [ ! -f "$MAKEFILE_DIR/Makefile" ]; then
            echo "Creating Makefile..."
            cat > "$MAKEFILE_DIR/Makefile" <<EOL
ARCHS = arm64
TARGET = iphone:clang:latest:7.0

include \$(THEOS)/makefiles/common.mk

TWEAK_NAME = BlockNet

BlockNet_FILES = BlockNet.m
BlockNet_FRAMEWORKS = UIKit
BlockNet_LIBRARIES = objc

include \$(THEOS)/makefiles/tweak.mk
EOL
            echo "Makefile created at $MAKEFILE_DIR/Makefile"
          else
            echo "Makefile already exists."
          fi

      - name: Build the Tweak
        run: |
          # Use the path of BlockNet.m to run the build
          BLOCKNET_M_PATH=${{ steps.find_blocknet_m.outputs.blocknet_m }}
          MAKEFILE_DIR=$(dirname "$BLOCKNET_M_PATH")

          # Navigate to the directory containing the Makefile and BlockNet.m
          cd "$MAKEFILE_DIR"
          
          echo "Building tweak with BlockNet.m in directory: $MAKEFILE_DIR"
          make clean
          make package

      - name: Upload the generated .dylib
        uses: actions/upload-artifact@v4
        with:
          name: BlockNet-dylib
          path: "$MAKEFILE_DIR/.theos/obj/iphone/debug/arm64/BlockNet.dylib"
